apiVersion: v1
kind: Service
metadata:
  name: firstk8sapp-service
  labels:
    app: firstk8sapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 4000 # load balancer port (i.e. the public port)
    targetPort: 80 # connect to contains on this port
    protocol: TCP
  selector:
    app: firstk8sapp # must point to pod label